[parity]
chain = "Recent.json"
[network]
interface = "0.0.0.0"
port = 30300
bootnodes = [
"enode://c9cc234d20db95dc031f0355ece2ed8c5efd61542d8d19854246ecf9f65afa0e9b06a0b50a600b5aa98719df28ffddab2c6e070d86633b13d446a1fb827adc2e@104.214.239.216:30300"
]
[rpc]
disable = true
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
password = ["node.pwds"]
[websockets]
disable = true
port = 8450
[mining]
engine_signer = "0xa0d5bf0ecdf9e4ddd8e508037b7e583b487d966a"
force_sealing = true
reseal_on_txs = "all"