[parity]
chain = "Recent.json"
[network]
interface = "0.0.0.0"
port = 30300
bootnodes = [
"enode://e86a30cae37dd92c1ea1428e95edd90255c48fc659398d9c532c0c2cd15e1558859a4acb1c29098c1857034086071fdd19187ac9426c2ccc026c6e9b4a0923ca@40.114.225.82:30300"
]
[rpc]
disable = true
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
password = ["node.pwds"]
[websockets]
disable = true
port = 8450
[mining]
engine_signer = "0x85bac7f03158d3a89e7b1d2feeefc3ba38dd39cd"
force_sealing = true
reseal_on_txs = "all"